# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_designs/AddReportInDB.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_Form(object):
    def setupUi(self, Add_Form):
        Add_Form.setObjectName("Add_Form")
        Add_Form.resize(670, 439)
        self.verticalLayout = QtWidgets.QVBoxLayout(Add_Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(Add_Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 4)
        self.spinBox = QtWidgets.QSpinBox(Add_Form)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 8, 1, 1, 3)
        self.add_item_btn = QtWidgets.QPushButton(Add_Form)
        self.add_item_btn.setObjectName("add_item_btn")
        self.gridLayout.addWidget(self.add_item_btn, 12, 1, 1, 3)
        self.label = QtWidgets.QLabel(Add_Form)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Add_Form)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(Add_Form)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 9, 1, 1, 3)
        self.label_4 = QtWidgets.QLabel(Add_Form)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 9, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Add_Form)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(Add_Form)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 7, 1, 1, 3)
        self.label_6 = QtWidgets.QLabel(Add_Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 4)
        self.label_7 = QtWidgets.QLabel(Add_Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 4)
        self.lineEdit = QtWidgets.QLineEdit(Add_Form)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 6, 1, 1, 3)
        self.label_9 = QtWidgets.QLabel(Add_Form)
        self.label_9.setStyleSheet("background-color: #00ffff;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 10, 1, 1, 2)
        self.dlt_btn = QtWidgets.QPushButton(Add_Form)
        self.dlt_btn.setObjectName("dlt_btn")
        self.gridLayout.addWidget(self.dlt_btn, 3, 0, 1, 1)
        self.choice_color_btn = QtWidgets.QPushButton(Add_Form)
        self.choice_color_btn.setObjectName("choice_color_btn")
        self.gridLayout.addWidget(self.choice_color_btn, 10, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(Add_Form)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 12, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Add_Form)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 10, 0, 1, 1)
        self.dlt_btn_once = QtWidgets.QPushButton(Add_Form)
        self.dlt_btn_once.setObjectName("dlt_btn_once")
        self.gridLayout.addWidget(self.dlt_btn_once, 2, 0, 1, 1)
        self.save_btn = QtWidgets.QPushButton(Add_Form)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 2, 1, 2, 1)
        self.info_btn = QtWidgets.QPushButton(Add_Form)
        self.info_btn.setObjectName("info_btn")
        self.gridLayout.addWidget(self.info_btn, 2, 2, 2, 1)
        self.change_color_btn = QtWidgets.QPushButton(Add_Form)
        self.change_color_btn.setObjectName("change_color_btn")
        self.gridLayout.addWidget(self.change_color_btn, 2, 3, 2, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Add_Form)
        QtCore.QMetaObject.connectSlotsByName(Add_Form)

    def retranslateUi(self, Add_Form):
        _translate = QtCore.QCoreApplication.translate
        Add_Form.setWindowTitle(_translate("Add_Form", "Редактор мероприятий"))
        self.add_item_btn.setText(_translate("Add_Form", "Добавить"))
        self.label.setText(_translate("Add_Form", "*Название:"))
        self.label_3.setText(_translate("Add_Form", "На какой рабочий день:"))
        self.label_4.setText(_translate("Add_Form", "Фиксированная дата:"))
        self.label_2.setText(_translate("Add_Form", "*Периодичность:"))
        self.label_6.setText(_translate("Add_Form", "Мероприятия в этот день"))
        self.label_7.setText(_translate("Add_Form", "Добавить новое событие"))
        self.dlt_btn.setText(_translate("Add_Form", "Удалить все связанные события"))
        self.choice_color_btn.setText(_translate("Add_Form", "Выбрать..."))
        self.label_8.setText(_translate("Add_Form", "Цвет ярлыка:"))
        self.dlt_btn_once.setText(_translate("Add_Form", "Удалить событие однажды"))
        self.save_btn.setText(_translate("Add_Form", "Сохранить"))
        self.info_btn.setText(_translate("Add_Form", "Подробнее"))
        self.change_color_btn.setText(_translate("Add_Form", "Изменить цвет.."))
