# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_designs/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 563)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI_designs/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 5, 2, 1, 1)
        self.upd_btn = QtWidgets.QPushButton(self.centralwidget)
        self.upd_btn.setObjectName("upd_btn")
        self.gridLayout_2.addWidget(self.upd_btn, 3, 1, 1, 1)
        self.expott_btn = QtWidgets.QPushButton(self.centralwidget)
        self.expott_btn.setObjectName("expott_btn")
        self.gridLayout_2.addWidget(self.expott_btn, 2, 1, 1, 1)
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setObjectName("add_btn")
        self.gridLayout_2.addWidget(self.add_btn, 1, 1, 1, 1)
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setMinimumSize(QtCore.QSize(410, 0))
        self.table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.table.setRowCount(6)
        self.table.setObjectName("table")
        self.table.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(184, 219, 255))
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(184, 219, 255))
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(184, 219, 255))
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(184, 219, 255))
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(184, 219, 255))
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(254, 180, 178))
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(254, 180, 178))
        self.table.setHorizontalHeaderItem(6, item)
        self.table.horizontalHeader().setVisible(True)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.horizontalHeader().setStretchLastSection(False)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setMinimumSectionSize(30)
        self.table.verticalHeader().setSortIndicatorShown(False)
        self.table.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.table, 0, 2, 5, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendar.sizePolicy().hasHeightForWidth())
        self.calendar.setSizePolicy(sizePolicy)
        self.calendar.setMaximumSize(QtCore.QSize(300, 300))
        self.calendar.setBaseSize(QtCore.QSize(300, 300))
        self.calendar.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.calendar.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.calendar.setObjectName("calendar")
        self.gridLayout_2.addWidget(self.calendar, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.action_add = QtWidgets.QAction(MainWindow)
        self.action_add.setObjectName("action_add")
        self.action_export = QtWidgets.QAction(MainWindow)
        self.action_export.setObjectName("action_export")
        self.action_upd = QtWidgets.QAction(MainWindow)
        self.action_upd.setObjectName("action_upd")
        self.action_close = QtWidgets.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.action_info = QtWidgets.QAction(MainWindow)
        self.action_info.setObjectName("action_info")
        self.menu.addAction(self.action_add)
        self.menu.addAction(self.action_export)
        self.menu.addAction(self.action_upd)
        self.menu.addAction(self.action_close)
        self.menu_2.addAction(self.action_info)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Планировщик отчетов"))
        self.upd_btn.setText(_translate("MainWindow", "Обновить праздничные дни"))
        self.upd_btn.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.expott_btn.setText(_translate("MainWindow", "Выгрузить график отчетов"))
        self.expott_btn.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.add_btn.setText(_translate("MainWindow", "Добавить событие в календарь"))
        self.add_btn.setShortcut(_translate("MainWindow", "Ctrl+N"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Пн"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Вт"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ср"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Чт"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Пт"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Сб"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Вс"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.menu_2.setTitle(_translate("MainWindow", "О программе"))
        self.action_add.setText(_translate("MainWindow", "Добавить событие в календарь"))
        self.action_add.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_export.setText(_translate("MainWindow", "Выгрузить график отчетов"))
        self.action_export.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_upd.setText(_translate("MainWindow", "Обновить праздничные дни"))
        self.action_upd.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.action_close.setText(_translate("MainWindow", "Выйти"))
        self.action_close.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.action_info.setText(_translate("MainWindow", "О программе"))
